Add text method to element
transceptor-technology/goleri pull request #8
Opened 2021-11-15 17:10 UTC by sujathakumar

2021-11-15 17:20 UTC, joente commented on go.mod
> +module github.com/iamneal/goleri
Can you exclude the go.mod file from the pull request?

2021-11-15 17:58 UTC, iamneal commented on result.go
> +	r.assignExpressionParts()
Ok we will take that out, thanks

2021-11-15 21:07 UTC, joente requested changes
Thanks for the pull request @iamneal!

Could you take a look at the test results? There are some lint issues with the pr. Otherwise it looks fine.

[Test CI](https://github.com/transceptor-technology/goleri/runs/4216855400?check_suite_focus=true) and [Test Lint](https://github.com/transceptor-technology/goleri/runs/4216855387?check_suite_focus=true)

2021-11-15 21:22 UTC, iamneal commented
yeah I'll take a look

2021-11-16 07:24 UTC, joente approved these changes

2021-11-16 07:24 UTC, merged

2021-11-16 09:41 UTC, joente commented
@iamneal ,

Maybe we could add a `GetNodeString` function to Result for retrieving a part of the string? 

Something like:

```go
// GetNodeString
func (r *Result) GetNodeString(n *Node) string {
	return r.expression[n.start:n.end]
}
```

This would require to parse the Node to the Result, but it keeps the Node struct light and does not unnecessary create a lot of new strings. (only when truly required).